add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[❯](bold green)" 
vimcmd_replace_one_symbol = "[❯](bold purple)" 
vimcmd_replace_symbol = "[❯](bold purple)" 
vimcmd_visual_symbol = "[❯](bold yellow)" 

[username]
disabled = false
show_always = true
format = " [$user]($style)@"

[directory]
format = "   [$path]($style)[$read_only]($read_only_style) "

[hostname]
ssh_only = false
disabled = false
